In [41]:
import pandas as pd
df = pd.read_csv('20260611_信用_经纪权限.csv',encoding='gbk')
df.head()

,QQ号,机构,姓名,国利,国际,中诚,平安,信唐,上田
0,2851162980,上海国泰海通证券资管,程千森,已开通;是好友,已开通;是好友,未申请;非好友,未申请;是好友,已开通;是好友,审核中;是好友
1,3005721528,平安证券,朱彤,已开通;是好友,未申请;是好友,未申请;非好友,未申请;非好友,已开通;是好友,未申请;是好友
2,3007254780,平安证券,黄永健,已开通;是好友,未申请;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友
3,3002143447,山西农联社,苏垚-高平农商银行,已开通;是好友,审核中;是好友,已开通;是好友,已开通;是好友,已开通;是好友,未申请;是好友
4,3003805527,森浦Sumscope,zhenbo.hu,已开通;是好友,未申请;是好友,未申请;非好友,未申请;非好友,未申请;非好友,审核中;非好友

In [42]:
cols = ['国利','国际','中诚','平安','信唐','上田']
df['已开通数量'] = df[cols].apply(lambda row: row.str.contains('已开通').sum(), axis=1)
df.head

<bound method NDFrame.head of              QQ号          机构         姓名       国利       国际       中诚       平安  \
0     2851162980  上海国泰海通证券资管        程千森  已开通;是好友  已开通;是好友  未申请;非好友  未申请;是好友
1     3005721528        平安证券         朱彤  已开通;是好友  未申请;是好友  未申请;非好友  未申请;非好友
2     3007254780        平安证券        黄永健  已开通;是好友  未申请;是好友  已开通;是好友  已开通;是好友
3     3002143447       山西农联社  苏垚-高平农商银行  已开通;是好友  审核中;是好友  已开通;是好友  已开通;是好友
4     3003805527  森浦Sumscope  zhenbo.hu  已开通;是好友  未申请;是好友  未申请;非好友  未申请;非好友
...          ...         ...        ...      ...      ...      ...      ...
3839  3007370322        世纪证券        陈洁心  未申请;非好友  未申请;非好友  未申请;非好友  未申请;非好友
3840  3003501833        国泰基金        蒋文博  未申请;非好友  未申请;非好友  未申请;非好友  未申请;非好友
3841  3007791657        世纪证券        袁静羽  未申请;非好友  未申请;非好友  未申请;非好友  未申请;非好友
3842  3007253733        世纪证券        崔凯琦  未申请;是好友  未申请;非好友  未申请;非好友  未申请;非好友
3843  2853233988      国泰海通证券        钮若洋  已开通;是好友  审核中;是好友  审核中;是好友  已开通;是好友

           信唐       上田  已开通数量
0     已开通;是好友  审核中;是好友      3
1     已开通;是好友  未申请;是好友      2
2     已开通;是好友  已开通;是好友      5
3     已开通;是好友  未申请;是好友      4
4     未申请;非好友  审核中;非好友      1
...       ...      ...    ...
3839  未申请;非好友  未申请;非好友      0
3840  未申请;非好友  未申请;非好友      0
3841  未申请;非好友  未申请;非好友      0
3842  未申请;非好友  未申请;非好友      0
3843  已开通;是好友  已开通;是好友      4

[3844 rows x 10 columns]>

In [43]:
df.sort_values('已开通数量', ascending=False).head(10)

,QQ号,机构,姓名,国利,国际,中诚,平安,信唐,上田,已开通数量
1396,3008665875,法巴农银理财,房冰婵,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
2515,2852872767,麦高证券,陈雨欣,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
2528,3003659934,广发证券,方小玲,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
1510,3007296568,申万菱信基金,丁界,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
1494,2850983055,招商基金,褚应芝,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
2556,3007791455,兴银理财,林葳杨,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
2559,3001287005,平安基金,朱深俊,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
1493,3007782098,招商基金,肖博亦,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
1492,2851162669,景顺长城基金,程玉雪,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6
1491,3007337848,招银理财,吴昊天,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,已开通;是好友,6

In [44]:
df.groupby('机构')['已开通数量'].mean().sort_values(ascending=False).head(10)

机构
中金基金        6.000000
汇丰晋信基金      6.000000
诺德基金        6.000000
申万菱信基金      6.000000
前海开源基金管理    6.000000
西部信托        6.000000
农银汇理基金管理    5.857143
国投瑞银基金      5.857143
招银理财        5.727273
金元顺安基金      5.666667
Name: 已开通数量, dtype: float64

In [45]:
df.groupby('机构')['已开通数量'].agg(['count','mean'])

        count      mean
机构
BGC HK      3  0.000000
一创证券       43  0.883721
一创证券资管      7  0.714286
万和证券        2  0.000000
万联证券       33  0.030303
...       ...       ...
首创证券       42  2.285714
鹏华基金       16  3.500000
麦高证券       35  1.571429
龙川农商行       1  0.000000
龙湾农商行       2  0.000000

[337 rows x 2 columns]

In [46]:
df_caculate = df.groupby('机构').agg(人数 = ('姓名', 'count'), 平均开通数量 = ('已开通数量','mean'))

In [50]:
df_caculate[df_caculate['人数'] > 10].sort_values('人数',ascending=False)

        人数    平均开通数量
机构
山西农联社  434  0.788018
山东农联社  173  0.167630
山西证券    56  0.125000
广发证券    54  1.074074
国金证券    50  0.760000
...    ...       ...
银华基金    11  2.272727
信达证券    11  0.000000
招银理财    11  5.727273
无锡农商行   11  0.000000
东海证券    11  1.363636

[95 rows x 2 columns]

In [49]:
result = df_caculate[df_caculate['人数'] > 10].sort_values('平均开通数量',ascending=False)
result.to_excel('机构统计.xlsx',index=True)

In [53]:
import pandas as pd
df = pd.read_csv('20260611_信用_经纪权限.csv', encoding='gbk')
cols = ['国利','国际','中诚','平安','信唐','上田']
df[cols].apply(lambda column: column.str.contains('已开通').sum()).sort_values(ascending=False)

国利    1036
平安     856
中诚     827
信唐     724
上田     664
国际     657
dtype: int64

In [54]:
import pandas as pd
df = pd.read_csv('20260611_信用_经纪权限.csv', encoding='gbk')
cols = ['国利','国际','中诚','平安','信唐','上田']
df[cols].apply(lambda column: column.str.contains('是好友').sum()).sort_values(ascending=False)

国利    2298
国际    2196
平安    2169
上田    2129
信唐    2119
中诚     978
dtype: int64